name: Frontend CI - Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      product_api_ip: { required: true, type: string }
      order_api_ip: { required: true, type: string }
      aks_cluster_name: { required: true, type: string }
      aks_resource_group: { required: true, type: string }
    secrets:
      azure_credentials: { required: true }

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}
      - name: Build and Push Frontend Image
        run: |
          az acr login --name ${{ env.ACR_LOGIN_SERVER }}
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend/
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
      - name: Trigger Frontend CD
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_call'
        uses: ./.github/workflows/frontend-cd.yml
        with:
          product_api_ip: ${{ inputs.product_api_ip }}
          order_api_ip: ${{ inputs.order_api_ip }}
          aks_cluster_name: ${{ inputs.aks_cluster_name }}
          aks_resource_group: ${{ inputs.aks_resource_group }}
        secrets: inherit
      - name: Logout from Azure
        run: az logout
